---
# Validation lab
# local users
fabric_name: MPLS_FABRIC

custom_structured_configuration_prefix: [ il_mgmt_]

# Optional, defaults to isis-sr
underlay_routing_protocol: isis-sr


# Disabling ISIS hello padding makes it easier with vEOS-lab.

isis_ti_lfa:
  enabled: true
  protection: link
  local_convergence_delay: 15000

# What should the defaults be?
isis_default_is_type: level-1-2
isis_default_circuit_type: level-2
isis_default_metric: 50
isis_advertise_passive_only: true

# iBGP is the default and only supported overlay protocol currently
# overlay_routing_protocol: ibgp
bgp_as: 65000
# If meshing PEs, client-to-client reflection can be turned off using rr bgp defaults.
# bgp_mesh_pes: true

# bgp peer groups passwords
bgp_peer_groups:
  MPLS_OVERLAY_PEERS:
    password: $1c$U4tL2vQP9QwZlxIV1K3/pw==
  RR_OVERLAY_PEERS:
    password: $1c$U4tL2vQP9QwZlxIV1K3/pw==

internal_vlan_order:
  allocation: ascending
  range:
    beginning: 3700
    ending: 3900

# Update p2p mtu
p2p_uplinks_mtu: 9214

aaa_root:
  secret:
    sha512_password: "$6$rfgRfL5cQa6pdiRz$60yX4YjN6C9UO5.yzWAEKYt8//qhIeXV5Bg931h0u3rtxtavbi1me6REcxEy7N1n/xtRAXH4ibeVDsxwwarxG1"

il_mgmt_load_interval:
  default: 2

# Timezone
il_mgmt_clock:
  timezone: Europe/Berlin

# DNS Servers
il_mgmt_name_server:
  source:
    vrf: MGMT
  nodes:
    - 172.22.60.20

il_mgmt_dns_domain: sjc.aristanetworks.com

# AAA Authentication
il_mgmt_aaa_authentication:
  login:
    default: local
    serial_console: local
  policies:
    on_failure_log: true
    on_success_log: true
    local:
      allow_nopassword: true

# Banners 
il_mgmt_banners:
  login: |
    This device is being used for the Inter.Link POC.
    Please contact the rightful owner(s) before making changes:

      Michael Pergament <mp@arista.com> - Systems Engineer
      Florian Hibler <florian@arista.com> - Advanced Services Engineer

    EOF
  motd: |
    This device is currently in use. If you need to access this device,
    you must contact its current owner.
    EOF

local_users:
  someuser:
    privilege: 15
    role: network-admin
    sha512_password: "someshapassword"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "someshapassword"

il_mgmt_management_api_http:
  enable_http: true
  enable_https: true
  enable_vrfs:
    default:
    MGMT:

# OOB Management network default gateway.
mgmt_gateway: 172.28.128.1

# NTP Servers IP or DNS
# First NTP server will be preferred
# Sourced from Managment VRF
il_mgmt_ntp:
  local_interface: 
    name: Management1
    vrf: MGMT
  servers:
  - name: poc-ntp.sjc.aristanetworks.com
    vrf: MGMT

# Sets the administrative subfield of IP/MAC VRF Route-Distinguishers and Route-Targets
# These are actually the defaults. No need to set anything really.
overlay_rd_type:
  admin_subfield: overlay_loopback
overlay_rt_type:
  admin_subfield: 65000

# BGP max-paths and ecmp
bgp_maximum_paths: 4
bgp_ecmp: 4
# evpn_ebgp_multihop: 10

# EVPN prevent readvertising routes
overlay_prevent_readvertise_to_server: true

# Adjust default bfd values if desired.
bfd_multihop:
  interval: 5000
  min_rx: 5000
  multiplier: 3


# Disable vlan aware bundles
# vxlan_vlan_aware_bundles: false

# P Routers
p:
  platform: vEOS-LAB
  defaults:
    loopback_ipv4_pool: 100.70.0.0/24
    loopback_ipv6_pool: "2000:1234:ffff:ffff::/64"
    # is_type: level-1-2
    node_sid_base: 300
    isis_system_id_prefix: '0000.0000'
    raw_eos_cli: |
      management security
         password encryption-key common
  nodes:
    p4:
      id: 4
      mgmt_ip: 10.30.30.104/24
    p6:
      id: 6
      mgmt_ip: 10.30.30.106/24

pe:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:00
    platform: vEOS-LAB
    loopback_ipv4_pool: 100.70.0.0/24
    loopback_ipv6_pool: "2000:1234:ffff:ffff::/64"
    is_type: level-1-2
    node_sid_base: 200
    isis_system_id_prefix: '0000.0001'
    # loopback_ipv4_offset: 3
    backbone_interface_speed: forced 100gfull
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    # spanning_tree_root_super: true
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    mpls_route_reflectors: [ rr7, rr8 ]
    raw_eos_cli: |
      management security
         password encryption-key common
  node_groups:
    frankfurt:
      filter:
        tenants: [ ]
        tags: [ frankfurt ]
      nodes:
        smm153:
          id: 1
          mgmt_ip: 172.28.135.121/20
        smm154:
          id: 2
          mgmt_ip: 172.28.135.163/20
        lyv558:
          id: 3
          mgmt_ip: 172.28.129.36/20
        lyv559:
          id: 4
          mgmt_ip: 172.28.135.18/20
    berlin:
      filter:
        tenants: [  ]
        tags: [ berlin ]
      nodes:
        smm311:
          id: 5
          mgmt_ip: 172.28.135.244/20
        smm312:
          id: 6
          mgmt_ip: 172.28.135.183/20
    amsterdam:
      filter:
        tenants: [  ]
        tags: [ amsterdam ]
      nodes:
        lyv582:
          id: 7
          mgmt_ip: 172.28.136.27/20
        smm313:
          id: 8
          mgmt_ip: 172.28.135.184/20
    nuremburg:
      filter:
        tenants: [  ]
        tags: [ nuremburg ]
      nodes:
        smm310:
          id: 9
          mgmt_ip: 172.28.135.207/20
    hamburg:
      filter:
        tenants: [  ]
        tags: [ hamburg ]
      nodes:
        cdv469:
          id: 10
          mgmt_ip: 172.28.136.166/20
rr:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 100.70.0.0/24
    loopback_ipv6_pool: "2000:1234:ffff:ffff::/64"
    is_type: level-1-2
    node_sid_base: 100
    isis_system_id_prefix: '0000.0002'
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
      - 'bgp route-reflector preserve-attributes always'
      # - 'no bgp client-to-client reflection' # If meshing PEs, client-to-client reflection can be turned off
    raw_eos_cli: |
      management security
         password encryption-key common
  node_groups:
    rr7-8:
      bgp_cluster_id: 7.7.7.7
      # evpn_gw:
      nodes:
        rr7:
          id: 7
          mgmt_ip: 10.30.30.107/24
        rr8:
          id: 8
          mgmt_ip: 10.30.30.108/24

connected_endpoints_keys:
  routers:
    type: router
  cpes:
    type: cpe

# backbone_interfaces:
#   p2p_links_ip_pools:
#     underlay_pool: 100.64.48.0/24
#   p2p_links_profiles:
#     default_bb_profile:
#       speed: 100full
#       mtu: 1500
#       isis_hello_padding: false
#       isis_metric: 60
#       ip_pool: underlay_pool
#       isis_circuit_type: level-2
#       ipv6_enable: true
#       isis_authentication_mode: md5
#       isis_authentication_key: $1c$sTNAlR6rKSw=
#   p2p_links:
#     # PE1 links
#     # If using IP unnumbered we don't even need 2 nodes or id or pool or a second interface...
#     # If pool is missing we default to unnumbered?
#     - nodes: [ pe1, pe2 ]
#       id: 1
#       interfaces: [ Ethernet1, Ethernet1 ]
#       profile: default_bb_profile
#       # bfd: false # should default to true
#     - nodes: [ pe1, p6 ]
#       id: 2
#       interfaces: [ Ethernet2, Ethernet2 ]
#       ip_pool: underlay_pool
#       speed: 100full
#       mtu: 1500
#       isis_hello_padding: true
#       isis_circuit_type: level-2
#       isis_metric: 60
#       # qos_profile: someprofile
#     - nodes: [ pe1, rr7 ]
#       id: 3
#       interfaces: [ Ethernet3, Ethernet2 ]
#       profile: default_bb_profile

#     # PE2 links
#     - nodes: [ pe2, rr8 ]
#       id: 4
#       interfaces: [ Ethernet3, Ethernet1 ]
#       profile: default_bb_profile
#     - nodes: [ pe2, pe3 ]
#       id: 5
#       interfaces: [ Ethernet2, Ethernet2 ]
#       profile: default_bb_profile

#     # PE3 links
#     - nodes: [ pe3, rr7 ]
#       id: 6
#       interfaces: [ Ethernet3, Ethernet1 ]
#       profile: default_bb_profile
#     - nodes: [ pe3, p4 ]
#       id: 7
#       interfaces: [ Ethernet1, Ethernet1 ]
#       profile: default_bb_profile

#     # P4 links
#     - nodes: [ p4, rr7 ]
#       id: 8
#       interfaces: [ Ethernet3, Ethernet4 ]
#       profile: default_bb_profile
#     - nodes: [ p4, pe5 ]
#       id: 9
#       interfaces: [ Ethernet2, Ethernet2 ]
#       profile: default_bb_profile

#     # PE5 links
#     - nodes: [ pe5, rr7 ]
#       id: 10
#       interfaces: [ Ethernet3, Ethernet3 ]
#       ip: ["unnumbered loopback0", "unnumbered loopback0"]
#     - nodes: [ pe5, p6 ]
#       id: 11
#       interfaces: [ Ethernet1, Ethernet1 ]
#       profile: default_bb_profile

#     # RR8 links
#     - nodes: [ rr7, rr8 ]
#       id: 12
#       port_channel:
#         mode: active
#         nodes_child_interfaces:
#           rr7: [ Ethernet5, Ethernet6 ]
#           rr8: [ Ethernet2, Ethernet3 ]
#       profile: default_bb_profile
