---
# Validation lab
# local users
fabric_name: MPLS_FABRIC

underlay_routing_protocol: isis-sr

isis_advertise_passive_only: true
# Disabling ISIS hello padding makes it easier with vEOS-lab.
isis_hello_padding: false
isis_ti_lfa:
  enabled: true
  protection: link
  local_convergence_delay: 15000

label_distribution:
  # protocol: ldp
  protocol: isis-sr # Should be the default.

overlay_routing_protocol: ibgp
bgp_as: 65000
# If meshing PEs, client-to-client reflection can be turned off using rr bgp defaults.
# bgp_mesh_pes: true

# bgp peer groups passwords
bgp_peer_groups:
  MPLS_OVERLAY_PEERS:
    password: $1c$U4tL2vQP9QwZlxIV1K3/pw==

internal_vlan_order:
  allocation: ascending
  range:
    beginning: 3700
    ending: 3900

# Update p2p mtu
p2p_uplinks_mtu: 1500

local_users:
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$nN0Xen3uF/RXr8mH$V4JuXG03QbzjjQMPKht0trSMDyOm4UhF13hQUWbBchxeNlQHttWn1R61er189k55GeRBoNCkgguOe9wh7lxxd."

custom_structured_configuration_management_api_http:
  enable_http: true
  enable_https: true
  enable_vrfs:
    default:
    MGMT:
# Cloud Vision server information
#cvp_instance_ip: 10.20.20.20
# This ingest key is set at CVP install time.
# cvp_ingestauth_key: somekey

# OOB Management network default gateway.
#mgmt_gateway: 10.30.30.1

# dns servers.
name_servers:
  - 10.20.20.13
  - 8.8.8.8

# NTP Servers IP or DNS
# First NTP server will be preferred
# Sourced from Managment VRF
# ntp_servers:
#   - 0.se.pool.ntp.org
#   - 1.se.pool.ntp.org

# Sets the administrative subfield of IP/MAC VRF Route-Distinguishers and Route-Targets
# These are actually the defaults. No need to set anything really.
overlay_rd_type:
  admin_subfield: overlay_loopback
overlay_rt_type:
  admin_subfield: 65000

# BGP max-paths and ecmp
bgp_maximum_paths: 4
bgp_ecmp: 4
# evpn_ebgp_multihop: 10

# EVPN prevent readvertising routes
overlay_prevent_readvertise_to_server: true

# Adjust default bfd values if desired.
bfd_multihop:
  interval: 5000
  min_rx: 5000
  multiplier: 3

# Disable vlan aware bundles
vxlan_vlan_aware_bundles: false

pe:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:00
    platform: vEOS-LAB
    loopback_ipv4_pool: 100.70.0.0/24
    loopback_ipv6_pool: "2000:1234:ffff:ffff::/64"
    node_sid_base: 200
    isis_system_id_prefix: '0000.0002'
    is_type: level-1-2
    # loopback_ipv4_offset: 3
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    # spanning_tree_root_super: true
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    mpls_route_reflectors: [ MUN-PE1, KAU-PE1 ]
    raw_eos_cli: |
      management security
         password encryption-key common
  node_groups:
    MUN1G:
      filter:
        tenants: [ TENANT_A ]
      nodes:
        MUN-PE3-1G:
          id: 1
          mgmt_ip: 192.168.0.24/24
        MUN-PE4-1G:
          id: 2
          mgmt_ip: 192.168.0.25/24
    MUN100G:
      filter:
        tenants: [ TENANT_A ]
      nodes:
        MUN-PE2:
          id: 4
          mgmt_ip: 192.168.0.23/24
    BAS100G:
      filter:
        tenants: [ TENANT_A ]
      nodes:
        BAS-PE1:
          id: 5
          mgmt_ip: 192.168.0.19/24
        BAS-PE2:
          id: 6
          mgmt_ip: 192.168.0.18/24
    KAU1G:
      filter:
        tenants: [ TENANT_A ]
      nodes:
        KAU-PE3-1G:
          id: 7
          mgmt_ip: 192.168.0.14/24
        KAU-PE4-1G:
          id: 8
          mgmt_ip: 192.168.0.15/24

    KAU100G:
      filter:
        tenants: [ TENANT_A ]
      nodes:
        KAU-PE2:
          id: 9
          mgmt_ip: 192.168.0.17/24


rr:
  defaults:
    platform: vEOS-LAB
    virtual_router_mac_address: 00:1c:73:00:dc:00
    loopback_ipv4_pool: 100.70.0.0/24
    loopback_ipv6_pool: "2000:1234:ffff:ffff::/64"
    is_type: level-1-2
    node_sid_base: 100
    isis_system_id_prefix: '0000.0002'
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    # isis_system_id_prefix: '0000.0002'
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
      - 'bgp route-reflector preserve-attributes always'
      # - 'no bgp client-to-client reflection' # If meshing PEs, client-to-client reflection can be turned off
    raw_eos_cli: |
      management security
         password encryption-key common
  node_groups:
    RRS:
      bgp_cluster_id: 7.7.7.7
      filter:
        tenants: [ TENANT_A ]
      nodes:
        MUN-PE1:
          id: 3
          mgmt_ip: 192.168.0.22/24
        KAU-PE1:
          id: 10
          mgmt_ip: 192.168.0.16/24


core_interfaces:
  p2p_links_ip_pools:
    - name: underlay_pool
      ipv4_pool: 100.64.48.0/24
  p2p_links_profiles:
    - name: default_bb_profile
      mtu: 1500
      isis_hello_padding: false
      ip_pool: underlay_pool
      isis_circuit_type: level-2
      ipv6_enable: true
      isis_authentication_mode: md5
      isis_authentication_key: $1c$sTNAlR6rKSw=
  p2p_links:
    # PE1 links
    - nodes: [ MUN-PE3-1G, MUN-PE1  ]
      id: 1
      interfaces: [ Ethernet3, Ethernet1 ]
      profile: default_bb_profile
    - nodes: [ MUN-PE3-1G, MUN-PE4-1G]
      id: 2
      interfaces: [ Ethernet4, Ethernet3 ]
      profile: default_bb_profile
    - nodes: [ MUN-PE4-1G, MUN-PE2  ]
      id: 3
      interfaces: [ Ethernet2, Ethernet1 ]
      profile: default_bb_profile
    - nodes: [ MUN-PE2, KAU-PE2  ]
      id: 4
      interfaces: [ Ethernet4, Ethernet1 ]
      profile: default_bb_profile
    - nodes: [ MUN-PE2, KAU-PE2  ]
      id: 5
      interfaces: [ Ethernet5, Ethernet2 ]
      profile: default_bb_profile
    - nodes: [ MUN-PE2, BAS-PE1  ]
      id: 6
      interfaces: [ Ethernet6, Ethernet1 ]
      profile: default_bb_profile
    - nodes: [ MUN-PE2, MUN-PE1 ]
      id: 7
      interfaces: [ Ethernet7, Ethernet5 ]
      profile: default_bb_profile
    - nodes: [ BAS-PE1, BAS-PE2 ]
      id: 8
      interfaces: [ Ethernet4, Ethernet4 ]
      profile: default_bb_profile
    - nodes: [ BAS-PE2, KAU-PE1 ]
      id: 9
      interfaces: [ Ethernet3, Ethernet6 ]
      profile: default_bb_profile
    - nodes: [ KAU-PE3-1G, KAU-PE1 ]
      id: 10
      interfaces: [ Ethernet1, Ethernet2 ]
      profile: default_bb_profile
    - nodes: [ KAU-PE3-1G, KAU-PE4-1G ]
      id: 11
      interfaces: [ Ethernet3, Ethernet2 ]
      profile: default_bb_profile
    - nodes: [ KAU-PE4-1G, KAU-PE2]
      id: 12
      interfaces: [ Ethernet3, Ethernet3 ]
      profile: default_bb_profile
    - nodes: [ KAU-PE2, KAU-PE1]
      id: 13
      interfaces: [ Ethernet6, Ethernet5 ]
      profile: default_bb_profile
    - nodes: [ MUN-PE1, KAU-PE1]
      id: 14
      interfaces: [ Ethernet4, Ethernet1 ]
      profile: default_bb_profile

node_type_keys:
  p:
    type: p
    mpls_lsr: true
    default_mpls_overlay_role: none
    default_overlay_routing_protocol: ibgp
    default_underlay_routing_protocol: isis-sr
  pe:
    type: pe
    mpls_lsr: true
    connected_endpoints: true
    default_mpls_overlay_role: client
    default_evpn_role: client
    network_services:
      l1: true
      l2: true
      l3: true
    mpls_ler: true
    default_overlay_routing_protocol: ibgp
    default_underlay_routing_protocol: isis-sr
    default_overlay_address_families: [ evpn ]
    default_evpn_encapsulation: mpls
  rr:
    type: rr
    mpls_lsr: true
    mpls_ler: true
    network_services:
      l1: true
      l2: true
      l3: true
    connected_endpoints: true
    default_mpls_overlay_role: server
    default_evpn_role: server
    default_overlay_routing_protocol: ibgp
    default_underlay_routing_protocol: isis-sr
    default_overlay_address_families: [ evpn ]
    default_evpn_encapsulation: mpls
  cpe:
    type: cpe
    connected_endpoints: true
    mlag_support: true
    network_services:
      l2: true
    underlay_router: false
    uplink_type: port-channel

connected_endpoints_keys:
  routers:
    type: router
  cpes:
    type: cpe

ansible_connection: httpapi
ansible_network_os: eos
ansible_user: cvpadmin
# should use vault for passwords - leaving un-encrypted for ease of sharing for labs
ansible_ssh_pass: cvp123!
ansible_become: yes
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
validation_mode_loose: true