tenants:
  TENANT_TEST:
    mac_vrf_rt_base: 10000
    pseudowire_rt_base: 1000
    point_to_point_services:
      - name: TEN_A_FRA_BER_eline_vlan_based_1
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
          - number: 1004
          - number: 1005
          - number: 1006
          - number: 1007
          - number: 1008
          - number: 1009
        endpoints:
          - id: 20000
            nodes: ['smm153', 'smm154']
            interfaces: [ Ethernet1/1 , Ethernet1/1]
            port_channel:
              mode: active
              short_esi: 0101:0202:0000
          - id: 30000
            nodes: ['smm311', 'smm312']
            interfaces: [ Ethernet1/1 , Ethernet1/1]
            port_channel:
              mode: active
              short_esi: 0202:0202
      - name: TEN_A_FRA_BER_eline_vlan_based_2
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
          - number: 1004
          - number: 1005
          - number: 1006
          - number: 1007
          - number: 1008
          - number: 1009
        endpoints:
          - id: 20010
            nodes: ['smm153', 'smm154']
            interfaces: [ Ethernet1/2 , Ethernet1/2]
            port_channel:
              mode: active
              short_esi: 0101:0202:0001
          - id: 30010
            nodes: ['smm311', 'smm312']
            interfaces: [ Ethernet1/2 , Ethernet1/2]
            port_channel:
              mode: active
              short_esi: 0202:0202
      - name: TEN_A_FRA_BER_eline_vlan_based_3
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
          - number: 1004
          - number: 1005
          - number: 1006
          - number: 1007
          - number: 1008
          - number: 1009
        endpoints:
          - id: 20020
            nodes: ['smm153', 'smm154']
            interfaces: [ Ethernet1/3 , Ethernet1/3]
            port_channel:
              mode: active
              short_esi: 0101:0202:0002
          - id: 30020
            nodes: ['smm311', 'smm312']
            interfaces: [ Ethernet1/3 , Ethernet1/3]
            port_channel:
              mode: active
              short_esi: 0202:0202
      - name: TEN_A_FRA_BER_eline_vlan_based_4
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
          - number: 1004
          - number: 1005
          - number: 1006
          - number: 1007
          - number: 1008
          - number: 1009
        endpoints:
          - id: 20030
            nodes: ['smm153', 'smm154']
            interfaces: [ Ethernet1/4 , Ethernet1/4]
            port_channel:
              mode: active
              short_esi: 0101:0202:0003
          - id: 30030
            nodes: ['smm311', 'smm312']
            interfaces: [ Ethernet1/4 , Ethernet1/4]
            port_channel:
              mode: active
              short_esi: 0202:0202
      - name: TEN_A_FRA_BER_eline_vlan_based_5
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
          - number: 1004
          - number: 1005
          - number: 1006
          - number: 1007
          - number: 1008
          - number: 1009
        endpoints:
          - id: 20040
            nodes: ['smm153', 'smm154']
            interfaces: [ Ethernet3/1 , Ethernet3/1]
            port_channel:
              mode: active
              short_esi: 0101:0202:0004
          - id: 30040
            nodes: ['smm311', 'smm312']
            interfaces: [ Ethernet3/1 , Ethernet3/1]
            port_channel:
              mode: active
              short_esi: 0202:0202
      - name: TEN_A_FRA_BER_eline_vlan_based_6
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
          - number: 1004
          - number: 1005
          - number: 1006
          - number: 1007
          - number: 1008
          - number: 1009
        endpoints:
          - id: 20050
            nodes: ['smm153', 'smm154']
            interfaces: [ Ethernet3/2 , Ethernet3/2]
            port_channel:
              mode: active
              short_esi: 0101:0202:0005
          - id: 30050
            nodes: ['smm311', 'smm312']
            interfaces: [ Ethernet3/2 , Ethernet3/2]
            port_channel:
              mode: active
              short_esi: 0202:0202
      - name: TEN_A_FRA_BER_eline_vlan_based_7
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
          - number: 1004
          - number: 1005
          - number: 1006
          - number: 1007
          - number: 1008
          - number: 1009
        endpoints:
          - id: 20060
            nodes: ['smm153', 'smm154']
            interfaces: [ Ethernet3/3 , Ethernet3/3]
            port_channel:
              mode: active
              short_esi: 0101:0202:0006
          - id: 30060
            nodes: ['smm311', 'smm312']
            interfaces: [ Ethernet3/3 , Ethernet3/3]
            port_channel:
              mode: active
              short_esi: 0202:0202
      - name: TEN_A_FRA_BER_eline_vlan_based_8
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
          - number: 1004
          - number: 1005
          - number: 1006
          - number: 1007
          - number: 1008
          - number: 1009
        endpoints:
          - id: 20070
            nodes: ['smm153', 'smm154']
            interfaces: [ Ethernet3/4 , Ethernet3/4]
            port_channel:
              mode: active
              short_esi: 0101:0202:0007
          - id: 30070
            nodes: ['smm311', 'smm312']
            interfaces: [ Ethernet3/4 , Ethernet3/4]
            port_channel:
              mode: active
              short_esi: 0202:0202
      - name: TEN_A_FRA_BER_eline_vlan_based_9
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
          - number: 1004
          - number: 1005
          - number: 1006
          - number: 1007
          - number: 1008
          - number: 1009
        endpoints:
          - id: 20080
            nodes: ['smm153', 'smm154']
            interfaces: [ Ethernet4/1 , Ethernet4/1]
            port_channel:
              mode: active
              short_esi: 0101:0202:0008
          - id: 30080
            nodes: ['smm311', 'smm312']
            interfaces: [ Ethernet4/1 , Ethernet4/1]
            port_channel:
              mode: active
              short_esi: 0202:0202
    l2vlans:
      10:
        name: TENANT_A_L2_SERVICE
        tags:
          - frankfurt
          - berlin
