tenants:
  TENANT_A:
    mac_vrf_rt_base: 10000
    pseudowire_rt_base: 1000
    mac_vrf_vni_base: 3000
    vlan_aware_bundle_number_base: 3000
    point_to_point_services:
      # simple p2p pseudowire, no redundancy, port-based
      - name: TEN_A_site2_site5_eline_port_based
        type: vpws-pseudowire
        endpoints: # Or alternative name: "termination"
          - id: 26
            nodes: ["MUN-PE3-1G"]
            interfaces: ["Ethernet1"]
          - id: 57
            nodes: ["KAU-PE3-1G"]
            interfaces: ["Ethernet2"]
        lldp_disable: true
