tenants:
  TENANT_A:
    # Not implemented yet
    l1_services:
      - name: TEN_A_site2_site5_eline
        type: vpws-pseudowire  # Should be default
        ids: [25, 57 ]
        nodes: ["MUN-PE3-1G", "KAU-PE3-1G"]
        interfaces: ["Ethernet1", "Ethernet2"]
    l2vlans:
      10:
        name: TENANT_A_L2_SERVICE
    mac_vrf_rt_base: 10000
    pw_rt_base: 1000
    vrfs:
      TENANT_A_WAN:
        address_families:
          - evpn
        svis: {}
        vrf_rt: 10