tenants:
  TENANT_A:
    mac_vrf_rt_base: 10000
    pseudowire_rt_base: 1000
    point_to_point_services:
      - name: TEN_A_FRA_BER_eline_vlan_based
        type: vpws-pseudowire
        subinterfaces:
          - number: 1000
          - number: 1001
          - number: 1002
          - number: 1003
        endpoints:
          - id: 10000
            nodes: ["smm153", "smm154"]
            interfaces: ["Ethernet1/1", "Ethernet1/1"]
            port_channel:
              mode: active
              short_esi: 0101:0202:0101
          - id: 20000
            nodes: ["smm311", "smm312"]
            interfaces: ["Ethernet1/1", "Ethernet1/1"]
            port_channel:
              mode: active
              short_esi: 0202:0202:0101
    l2vlans:
      10:
        name: TENANT_A_L2_SERVICE
        tags:
          - frankfurt
          - berlin