---
il_common_tcam_profile:
  system: florian-interlink-v1
  profiles:
    traffic_policy: "{{lookup('file', '{{ root_dir }}/TCAM_TRAFFIC_POLICY.conf')}}"

il_common_ip_extcommunity_lists:
  INTERNET-DEFAULT-COMM:
    - type: permit 
      extcommunities: "rt 65000:65000"

il_common_route_maps:
  FIB-FILTER-INTERNET-IN-RM:
    sequence_numbers:
      # 5:
      #   type: permit
      #   match:
      #     - "ip address prefix-list DEFAULT-PL"
      10:
        type: permit
        match:
          - "source-protocol connected"
      20:
        type: permit
        match:
          - "tag 50000"
      30:
        type: deny
  TAG-INTERNET-IN-RM:
    sequence_numbers:
      10:
        type: permit
        match:
          - "extcommunity INTERNET-DEFAULT-COMM"
        set:
          - "tag 50000"
      30:
        type: permit
  TAG-DEFAULT-ONLY-RM:
    sequence_numbers:
      10:
        type: permit
        set:
          - "extcommunity rt 65000:65000 additive"

  LOCAL_DEFAULT_LEAK_RM:
    sequence_numbers:
      10:
        type: permit
        set: 
          - "tag 50000"
  DENY-ALL-RM:
    sequence_numbers:
      10:
        type: deny

il_common_router_bgp:
  peer_groups:
    MPLS-OVERLAY-PEERS:
      type: evpn
      route_map_in: TAG-INTERNET-IN-RM

router_general:
  fast_failover: true
  vrfs:
    PREMIUM1:
      fib_policy: FIB-FILTER-INTERNET-IN-RM
      # leak_routes:
      #   - source_vrf: INTERNET
      #     subscribe_policy: LOCAL_DEFAULT_LEAK_RM